using System;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Windows.Forms;
using PensionMgmt.Data;
using PensionMgmt.Services;

namespace PensionMgmt.Forms
{
    public class EmployeesPanel : UserControl
    {
        private readonly DbAccess _db = new DbAccess();
        private readonly bool _readOnly;
        private DataGridView dgv;
        private TextBox txtSearch;
        private Panel pnlForm;
        private bool _isEditing;
        private string _editingId;

        // txtEmpId removed from Add form — ID is now auto-generated by the database
        private TextBox txtName, txtDept, txtSalary;
        private ComboBox cmbRank, cmbStatus;
        private DateTimePicker dtpBirth, dtpJoining;

        public EmployeesPanel(bool readOnly = false)
        {
            _readOnly = readOnly;
            this.BackColor = Color.FromArgb(245, 247, 250);
            BuildUI();
            LoadGrid();
        }

        private void BuildUI()
        {
            Label lbl = new Label
            {
                Text = _readOnly ? "Employees (View Only)" : "Employee Management",
                Font = new Font("Segoe UI", 15f, FontStyle.Bold),
                ForeColor = Color.FromArgb(25, 45, 80),
                Bounds = new Rectangle(20, 16, 400, 34)
            };
            this.Controls.Add(lbl);

            Label lSearch = new Label { Text = "Search:", Bounds = new Rectangle(20, 60, 60, 26), TextAlign = ContentAlignment.MiddleLeft };
            txtSearch = new TextBox { Bounds = new Rectangle(82, 60, 260, 26) };
            txtSearch.TextChanged += (s, e) => LoadGrid(txtSearch.Text.Trim());
            this.Controls.Add(lSearch);
            this.Controls.Add(txtSearch);

            if (!_readOnly)
            {
                Button btnAdd = new Button
                {
                    Text = "+ Add Employee",
                    Bounds = new Rectangle(360, 56, 140, 30),
                    BackColor = Color.FromArgb(25, 45, 80),
                    ForeColor = Color.White,
                    FlatStyle = FlatStyle.Flat,
                    Cursor = Cursors.Hand
                };
                btnAdd.FlatAppearance.BorderSize = 0;
                btnAdd.Click += (s, e) => ShowForm(editMode: false);
                this.Controls.Add(btnAdd);
            }

            dgv = new DataGridView
            {
                Bounds = new Rectangle(20, 100, this.Width - 40, 300),
                Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right,
                ReadOnly = true,
                AllowUserToAddRows = false,
                SelectionMode = DataGridViewSelectionMode.FullRowSelect,
                AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill,
                BackgroundColor = Color.White,
                BorderStyle = BorderStyle.None,
                RowHeadersVisible = false,
                MultiSelect = false
            };
            dgv.DoubleClick += Dgv_DoubleClick;
            this.Controls.Add(dgv);

            if (!_readOnly)
            {
                Button btnEdit = new Button
                {
                    Text = "✎ Edit Selected",
                    Bounds = new Rectangle(20, 410, 140, 30),
                    BackColor = Color.DarkOrange,
                    ForeColor = Color.White,
                    FlatStyle = FlatStyle.Flat,
                    Cursor = Cursors.Hand
                };
                btnEdit.FlatAppearance.BorderSize = 0;
                btnEdit.Click += (s, e) => EditSelected();
                this.Controls.Add(btnEdit);

                Button btnDel = new Button
                {
                    Text = "✖ Delete Selected",
                    Bounds = new Rectangle(170, 410, 150, 30),
                    BackColor = Color.Firebrick,
                    ForeColor = Color.White,
                    FlatStyle = FlatStyle.Flat,
                    Cursor = Cursors.Hand
                };
                btnDel.FlatAppearance.BorderSize = 0;
                btnDel.Click += (s, e) => DeleteSelected();
                this.Controls.Add(btnDel);
            }

            pnlForm = new Panel
            {
                BackColor = Color.White,
                Bounds = new Rectangle(20, 450, this.Width - 40, 280),
                Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right,
                Visible = false
            };
            BuildFormPanel();
            this.Controls.Add(pnlForm);
        }

        private void BuildFormPanel()
        {
            int col1 = 10, col2 = 230, lw = 130, tw = 160, rh = 28, gap = 40;

            Label lHead = new Label
            {
                Text = "Employee Details",
                Font = new Font("Segoe UI", 11f, FontStyle.Bold),
                ForeColor = Color.FromArgb(25, 45, 80),
                Bounds = new Rectangle(10, 8, 300, 28)
            };
            pnlForm.Controls.Add(lHead);

            int y = 44;

            // Employee ID is auto-generated — show a read-only info label instead of a textbox
            Label lAutoId = new Label
            {
                Text = "Employee ID:",
                Bounds = new Rectangle(col1, y, lw, rh),
                TextAlign = ContentAlignment.MiddleLeft
            };
            Label lblAutoIdNote = new Label
            {
                Text = "Auto-generated by system",
                ForeColor = Color.Gray,
                Font = new Font("Segoe UI", 9f, FontStyle.Italic),
                Bounds = new Rectangle(col1 + lw + 4, y, tw, rh),
                TextAlign = ContentAlignment.MiddleLeft
            };
            pnlForm.Controls.Add(lAutoId);
            pnlForm.Controls.Add(lblAutoIdNote);

            AddFormRow(pnlForm, "Full Name *", col2, y, lw, out txtName); y += gap;
            AddFormRow(pnlForm, "Department *", col1, y, lw, out txtDept);

            Label lRank = new Label { Text = "Rank *", Bounds = new Rectangle(col2, y, lw, rh), TextAlign = ContentAlignment.MiddleLeft };
            cmbRank = new ComboBox { Bounds = new Rectangle(col2 + lw + 4, y, tw, rh), DropDownStyle = ComboBoxStyle.DropDownList };
            cmbRank.Items.AddRange(new[] { "Secretary", "Joint Secretary", "Deputy Secretary", "Senior Assistant", "Assistant" });
            cmbRank.SelectedIndex = 4;
            pnlForm.Controls.Add(lRank);
            pnlForm.Controls.Add(cmbRank);
            y += gap;

            AddFormRow(pnlForm, "Basic Salary *", col1, y, lw, out txtSalary);

            Label lStatus = new Label { Text = "Status", Bounds = new Rectangle(col2, y, lw, rh), TextAlign = ContentAlignment.MiddleLeft };
            cmbStatus = new ComboBox { Bounds = new Rectangle(col2 + lw + 4, y, tw, rh), DropDownStyle = ComboBoxStyle.DropDownList };
            cmbStatus.Items.AddRange(new[] { "Active", "Retired", "Suspended" });
            cmbStatus.SelectedIndex = 0;
            pnlForm.Controls.Add(lStatus);
            pnlForm.Controls.Add(cmbStatus);
            y += gap;

            Label lBirth = new Label { Text = "Date of Birth *", Bounds = new Rectangle(col1, y, lw, rh), TextAlign = ContentAlignment.MiddleLeft };
            dtpBirth = new DateTimePicker { Bounds = new Rectangle(col1 + lw + 4, y, tw, rh), Format = DateTimePickerFormat.Short, Value = DateTime.Today.AddYears(-30) };
            pnlForm.Controls.Add(lBirth);
            pnlForm.Controls.Add(dtpBirth);

            Label lJoin = new Label { Text = "Joining Date *", Bounds = new Rectangle(col2, y, lw, rh), TextAlign = ContentAlignment.MiddleLeft };
            dtpJoining = new DateTimePicker { Bounds = new Rectangle(col2 + lw + 4, y, tw, rh), Format = DateTimePickerFormat.Short };
            pnlForm.Controls.Add(lJoin);
            pnlForm.Controls.Add(dtpJoining);
            y += gap;

            Button btnSave = new Button
            {
                Text = "✔ Save",
                Bounds = new Rectangle(col1, y, 120, 30),
                BackColor = Color.FromArgb(25, 45, 80),
                ForeColor = Color.White,
                FlatStyle = FlatStyle.Flat,
                Cursor = Cursors.Hand
            };
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.Click += BtnSave_Click;
            pnlForm.Controls.Add(btnSave);

            Button btnCancel = new Button
            {
                Text = "Cancel",
                Bounds = new Rectangle(col1 + 130, y, 90, 30),
                FlatStyle = FlatStyle.Flat,
                Cursor = Cursors.Hand
            };
            btnCancel.Click += (s, e) => pnlForm.Visible = false;
            pnlForm.Controls.Add(btnCancel);
        }

        private void AddFormRow(Panel parent, string label, int x, int y, int lw, out TextBox txt)
        {
            Label l = new Label { Text = label, Bounds = new Rectangle(x, y, lw, 28), TextAlign = ContentAlignment.MiddleLeft };
            txt = new TextBox { Bounds = new Rectangle(x + lw + 4, y, 160, 28) };
            parent.Controls.Add(l);
            parent.Controls.Add(txt);
        }

        private void LoadGrid(string search = "")
        {
            DataTable dt;
            string sql;
            if (string.IsNullOrEmpty(search))
            {
                sql = "SELECT EmployeeId, FullName, Department, Rank, BasicSalary, DateOfBirth, JoiningDate, Status FROM Employees ORDER BY FullName";
                dt = _db.GetTable(sql);
            }
            else
            {
                sql = "SELECT EmployeeId, FullName, Department, Rank, BasicSalary, DateOfBirth, JoiningDate, Status " +
                      "FROM Employees WHERE EmployeeId LIKE @s OR FullName LIKE @s ORDER BY FullName";
                dt = _db.GetTable(sql, new SqlParameter("@s", "%" + search + "%"));
            }
            dgv.DataSource = dt;
        }

        private void ShowForm(bool editMode)
        {
            _isEditing = editMode;
            pnlForm.Visible = true;
            if (!editMode)
            {
                // Clear all fields for a fresh add — no Employee ID field to clear
                txtName.Clear();
                txtDept.Clear();
                txtSalary.Clear();
                cmbRank.SelectedIndex = 4;
                cmbStatus.SelectedIndex = 0;
                dtpBirth.Value = DateTime.Today.AddYears(-30);
                dtpJoining.Value = DateTime.Today;
                _editingId = null;
            }
        }

        private void Dgv_DoubleClick(object sender, EventArgs e)
        {
            if (!_readOnly) EditSelected();
        }

        private void EditSelected()
        {
            if (dgv.CurrentRow == null) return;
            DataRow row = ((DataTable)dgv.DataSource).Rows[dgv.CurrentRow.Index];
            _editingId = row["EmployeeId"].ToString();
            txtName.Text = row["FullName"].ToString();
            txtDept.Text = row["Department"].ToString();
            txtSalary.Text = row["BasicSalary"].ToString();
            cmbRank.Text = row["Rank"].ToString();
            cmbStatus.Text = row["Status"].ToString();
            dtpBirth.Value = Convert.ToDateTime(row["DateOfBirth"]);
            dtpJoining.Value = Convert.ToDateTime(row["JoiningDate"]);
            ShowForm(editMode: true);
        }

        private void DeleteSelected()
        {
            if (dgv.CurrentRow == null) { MessageBox.Show("Select an employee first."); return; }
            DataRow row = ((DataTable)dgv.DataSource).Rows[dgv.CurrentRow.Index];
            string id = row["EmployeeId"].ToString();
            string name = row["FullName"].ToString();

            if (MessageBox.Show($"Delete {name} ({id})?", "Confirm Delete",
                    MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                int n = _db.Execute("DELETE FROM Employees WHERE EmployeeId=@id", new SqlParameter("@id", id));
                if (n > 0)
                {
                    AuditLogger.Log("Employee Deleted", id, name,
                        string.Format("Employee '{0}' (ID: {1}) was deleted from the system.", name, id));
                    MessageBox.Show("Employee deleted.");
                    LoadGrid();
                }
            }
        }

        private void BtnSave_Click(object sender, EventArgs e)
        {
            // Validate fields (no Employee ID field anymore)
            if (string.IsNullOrWhiteSpace(txtName.Text) ||
                string.IsNullOrWhiteSpace(txtDept.Text) ||
                string.IsNullOrWhiteSpace(txtSalary.Text))
            {
                MessageBox.Show("Please fill all required fields.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            if (!decimal.TryParse(txtSalary.Text, out decimal salary) || salary <= 0)
            {
                MessageBox.Show("Enter a valid Basic Salary.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            if (dtpBirth.Value >= dtpJoining.Value)
            {
                MessageBox.Show("Joining Date must be after Date of Birth.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            string name = txtName.Text.Trim();
            string dept = txtDept.Text.Trim();
            string rank = cmbRank.Text;
            string status = cmbStatus.Text;
            DateTime dob = dtpBirth.Value.Date;
            DateTime doj = dtpJoining.Value.Date;

            if (_isEditing)
            {
                int n = _db.Execute(
                    "UPDATE Employees SET FullName=@n, Department=@d, Rank=@r, " +
                    "BasicSalary=@s, DateOfBirth=@b, JoiningDate=@j, Status=@st " +
                    "WHERE EmployeeId=@id",
                    new SqlParameter("@n", name),
                    new SqlParameter("@d", dept),
                    new SqlParameter("@r", rank),
                    new SqlParameter("@s", salary),
                    new SqlParameter("@b", dob),
                    new SqlParameter("@j", doj),
                    new SqlParameter("@st", status),
                    new SqlParameter("@id", _editingId));

                if (n > 0)
                {
                    AuditLogger.Log("Employee Updated", _editingId, name,
                        string.Format("Employee '{0}' (ID: {1}) updated. Dept: {2}, Rank: {3}, Salary: {4:N0}, Status: {5}.",
                            name, _editingId, dept, rank, salary, status));
                    MessageBox.Show("Employee updated successfully.");
                    pnlForm.Visible = false;
                    LoadGrid();
                }
            }
            else
            {
                // INSERT without EmployeeId — database computes it automatically
                _db.Execute(
                    "INSERT INTO Employees (FullName, Department, Rank, BasicSalary, DateOfBirth, JoiningDate, Status) " +
                    "VALUES (@n, @d, @r, @s, @b, @j, @st)",
                    new SqlParameter("@n", name),
                    new SqlParameter("@d", dept),
                    new SqlParameter("@r", rank),
                    new SqlParameter("@s", salary),
                    new SqlParameter("@b", dob),
                    new SqlParameter("@j", doj),
                    new SqlParameter("@st", status));

                // Read back the auto-generated EmployeeId
                object result = _db.ExecuteScalar(
                    "SELECT TOP 1 EmployeeId FROM Employees ORDER BY Id DESC");
                string newEmpId = result?.ToString() ?? "N/A";

                AuditLogger.Log("Employee Added", newEmpId, name,
                    string.Format("New employee '{0}' (ID: {1}) added. Dept: {2}, Rank: {3}, Salary: {4:N0}, Status: {5}.",
                        name, newEmpId, dept, rank, salary, status));

                MessageBox.Show(string.Format("Employee added successfully.\nAssigned Employee ID: {0}", newEmpId));
                pnlForm.Visible = false;
                LoadGrid();

                if (status == "Retired")
                    TryAutoCreatePendingPayout(newEmpId, name, salary, dob, doj, rank);
            }
        }

        private void TryAutoCreatePendingPayout(
            string empId, string name, decimal salary,
            DateTime dob, DateTime doj, string rank)
        {
            bool eligible = PensionCalculator.Calculate(
                salary, dob, doj, rank,
                out decimal monthly, out decimal lump, out string msg);

            if (!eligible) return;

            object existingCount = _db.ExecuteScalar(
                "SELECT COUNT(*) FROM Payouts WHERE EmployeeId = @id",
                new SqlParameter("@id", empId));
            if (Convert.ToInt32(existingCount) > 0) return;

            _db.Execute(
                "INSERT INTO Payouts (EmployeeId, FullName, MonthlyPension, LumpSum, ProcessedDate, Notes, Status) " +
                "VALUES (@id, @name, @m, @l, @d, @notes, 'Pending')",
                new SqlParameter("@id", empId),
                new SqlParameter("@name", name),
                new SqlParameter("@m", monthly),
                new SqlParameter("@l", lump),
                new SqlParameter("@d", DateTime.Today),
                new SqlParameter("@notes", "Auto-generated on employee registration as Retired."));

            AuditLogger.Log("Payout Pending", empId, name,
                string.Format("Auto-generated Pending payout for retired employee '{0}'. Monthly: BDT {1:N2}, Lump Sum: BDT {2:N2}.",
                    name, monthly, lump));

            MessageBox.Show(
                string.Format(
                    "Employee '{0}' is eligible for pension and is marked as Retired.\n\n" +
                    "Monthly Pension : BDT {1:N2}\n" +
                    "Lump Sum        : BDT {2:N2}\n\n" +
                    "A Pending payout has been automatically created.\n" +
                    "Go to Pension Payouts to approve it.",
                    name, monthly, lump),
                "Auto Payout Created", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }
    }
}